# Generated by Django 5.2.11 on 2026-02-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.CharField(max_length=50, verbose_name='tarefa')),
                ('concluida', models.BooleanField(default=False, verbose_name='concluida')),
            ],
        ),
    ]
